### ISSUE TITLE
inspera

### ISSUE THREAD

**Issue by cyberir** [Scrut1ny/Hypervisor-Phantom#13]
How can I bypass inspera in virtualbox?
Please explain the steps step by step?
Inside the inspera software, it gives me a virtual machine error

**Comment by Scrut1ny** [comment]
1. Figure it out, I provide the details already in the repo.
2. No, you need to figure that out yourself. It's not hard.
3. If you can't bypass the software via VirtualBox it's probably not possible using VirtualBox.
