### ISSUE TITLE
Phoenix BIOS Editor not available

### ISSUE THREAD

**Issue by aljabr** [Scrut1ny/Hypervisor-Phantom#15]
Hi,
the link is not working
[Phoenix BIOS Editor](https://mega.nz/file/cek3ARwR#0L3mXNAlknF0zJQPOmtqPoyAvF5exviI3zw_BfRixOk)

**Comment by Scrut1ny** [comment]
IT got removed I guess or expired, idk. Wasn't an official link anyway.

**Comment by Scrut1ny** [comment]
@aljabr Found a copy of it somewhere, looks legit and good to me.

https://theretroweb.com/drivers/208
