### ISSUE TITLE
weird graphical glitch

### ISSUE THREAD

**Issue by D-06** [Scrut1ny/Hypervisor-Phantom#16]
![Screenshot From 2024-09-21 16-38-30](https://github.com/user-attachments/assets/545a4d59-c6ad-419b-ab55-2a827e1e73ff)
i just compile qemu and install win11 but this happend

**Comment by Scrut1ny** [comment]
Only use direct display from passed through GPU or else you're detected. Or just use looking glass, won't bypass some anti cheats with that though most likely.
