### ISSUE TITLE
Can you share how to install it?

### ISSUE THREAD

**Issue by vpn28** [Scrut1ny/Hypervisor-Phantom#2]
Can we have an installation guide please?
I have a competition with Pearson Vue (Onvue) tomorrow

**Comment by Scrut1ny** [comment]
An installation guide for what?

**Comment by vpn28** [comment]
> An installation guide for what?

Can bypass pearson vue?

**Comment by Scrut1ny** [comment]
Yes, I've bypassed it. I'm currently working on the HDCP issue though.

**Comment by vpn28** [comment]
> Yes, I've bypassed it. I'm currently working on the HDCP issue though.

Oh. Can I contact you? I have a competition with Pearson Vue (Onvue) tomorrow.

**Comment by Scrut1ny** [comment]
yeah sure, you want to chat on Discord?

**Comment by vpn28** [comment]
Yep, anywhere

**Comment by Scrut1ny** [comment]
gotcha
