### ISSUE TITLE
Not spoofing

### ISSUE THREAD

**Issue by Zzzeeroo** [Scrut1ny/Hypervisor-Phantom#4]
Hello, I ran the .sh and installed qemu and when I install a VM it still does not spoof these 2 settings 
![Screenshot from 2024-04-21 02-26-28](https://github.com/Scrut1ny/Hypervisor-Phantom/assets/20956350/2559a613-a1f0-4747-8b8b-e6d8cbd705f9)
![Screenshot from 2024-04-21 02-27-05](https://github.com/Scrut1ny/Hypervisor-Phantom/assets/20956350/8efb2a1d-5224-4baa-bb3f-2eb19a308445)
Is it not supposed to spoof these? Do you know how to spoof them or does anyone on here know how to?

**Comment by Scrut1ny** [comment]
I'm still working on the `.sh` file, the it didn't even actually build the custom version of the program. You need certain dependies that aren't listed on the `.sh` script. I've been fixing it though I know whats missing.
